/*
 * This class contains the Main method and user interface for the MileageAdder
 * application. It instantiates and calls methods from the MileageAdder and 
 * LogBuilder classes.
*/
package mileage;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.awt.*;
import java.io.*;
import java.nio.file.Files;
import javax.swing.JOptionPane;

public class MileageUI extends javax.swing.JFrame {

    public static Path workingDirectory;
    private double avgWeeklyMileage;
    private final WeeklyMileagePanel weeklyPanel;
    private boolean mustDeleteFile;
    private String filename, yearToBuildString;
    private Path newFile;
    
    public MileageUI() {
        initComponents();
        weeklyPanel = new WeeklyMileagePanel();
        weeklyPanel.setLocation(50, 200);
        weeklyPanel.setSize(270, 30);
        add(weeklyPanel);
        WorkingDirectoryMenuItem.doClick(1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WorkingDirectoryChooser = new javax.swing.JFileChooser();
        LogBuilderFrame = new javax.swing.JFrame();
        LogBuilderTxtLabel = new javax.swing.JLabel();
        LogBuilderBuildButton = new javax.swing.JButton();
        LogBuilderCompleteNotification = new javax.swing.JLabel();
        LogBuilderCloseButton = new javax.swing.JButton();
        LogBuilderYearField = new javax.swing.JTextField();
        LogBuilderNameLabel = new javax.swing.JLabel();
        LogBuilderNameField = new javax.swing.JTextField();
        LogBuilderYearLabel = new javax.swing.JLabel();
        FromLabel = new javax.swing.JLabel();
        ToLabel = new javax.swing.JLabel();
        TotalMileageOutputText = new javax.swing.JTextField();
        TotalMileageLabel = new javax.swing.JLabel();
        FromMonthComboBox = new javax.swing.JComboBox();
        ToMonthComboBox = new javax.swing.JComboBox();
        FromYearComboBox = new javax.swing.JComboBox();
        ToYearComboBox = new javax.swing.JComboBox();
        FromDayComboBox = new javax.swing.JComboBox();
        ToDayComboBox = new javax.swing.JComboBox();
        MainMenuBar = new javax.swing.JMenuBar();
        MainMenuDropdown = new javax.swing.JMenu();
        WorkingDirectoryMenuItem = new javax.swing.JMenuItem();
        LogBuilderMenuItem = new javax.swing.JMenuItem();
        ExitMenuItem = new javax.swing.JMenuItem();

        WorkingDirectoryChooser.setApproveButtonMnemonic(1);
        WorkingDirectoryChooser.setCurrentDirectory(workingDirectory.toFile());
        WorkingDirectoryChooser.setDialogTitle("Choose working directory.");
        WorkingDirectoryChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        LogBuilderFrame.setLocationByPlatform(true);
        LogBuilderFrame.setMinimumSize(new java.awt.Dimension(350, 177));
        LogBuilderFrame.setResizable(false);

        LogBuilderTxtLabel.setText(".txt");

        LogBuilderBuildButton.setText("Build");
        LogBuilderBuildButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LogBuilderBuildButton.setSelected(true);
        LogBuilderBuildButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBuilderBuildButtonActionPerformed(evt);
            }
        });

        LogBuilderCompleteNotification.setText("Complete");
        LogBuilderCompleteNotification.setFocusable(false);

        LogBuilderCloseButton.setText("Close");
        LogBuilderCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBuilderCloseButtonActionPerformed(evt);
            }
        });

        LogBuilderYearField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LogBuilderYearFieldKeyPressed(evt);
            }
        });

        LogBuilderNameLabel.setText("File name");

        LogBuilderNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LogBuilderNameFieldKeyPressed(evt);
            }
        });

        LogBuilderYearLabel.setText("Year to build:");

        javax.swing.GroupLayout LogBuilderFrameLayout = new javax.swing.GroupLayout(LogBuilderFrame.getContentPane());
        LogBuilderFrame.getContentPane().setLayout(LogBuilderFrameLayout);
        LogBuilderFrameLayout.setHorizontalGroup(
            LogBuilderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogBuilderFrameLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(LogBuilderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LogBuilderFrameLayout.createSequentialGroup()
                        .addComponent(LogBuilderYearLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogBuilderYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LogBuilderCompleteNotification))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LogBuilderFrameLayout.createSequentialGroup()
                        .addComponent(LogBuilderNameLabel)
                        .addGap(10, 10, 10)
                        .addComponent(LogBuilderNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(LogBuilderTxtLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LogBuilderFrameLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(LogBuilderBuildButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LogBuilderCloseButton)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        LogBuilderFrameLayout.setVerticalGroup(
            LogBuilderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogBuilderFrameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(LogBuilderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogBuilderNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LogBuilderFrameLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(LogBuilderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogBuilderNameLabel)
                            .addComponent(LogBuilderTxtLabel))))
                .addGap(11, 11, 11)
                .addGroup(LogBuilderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogBuilderYearLabel)
                    .addComponent(LogBuilderYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogBuilderCompleteNotification))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LogBuilderFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogBuilderBuildButton)
                    .addComponent(LogBuilderCloseButton))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GetMileage");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(392, 298));
        setResizable(false);

        FromLabel.setText("From");

        ToLabel.setText("To");

        TotalMileageOutputText.setEditable(false);
        TotalMileageOutputText.setToolTipText("");

        TotalMileageLabel.setText("Total mileage for this period was...");

        FromMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        FromMonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromMonthComboBoxActionPerformed(evt);
            }
        });

        ToMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        ToMonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToMonthComboBoxActionPerformed(evt);
            }
        });

        FromYearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        FromYearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromYearComboBoxActionPerformed(evt);
            }
        });

        ToYearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        ToYearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToYearComboBoxActionPerformed(evt);
            }
        });

        FromDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        FromDayComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromDayComboBoxActionPerformed(evt);
            }
        });

        ToDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        ToDayComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToDayComboBoxActionPerformed(evt);
            }
        });

        MainMenuDropdown.setText("File");
        MainMenuDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuDropdownActionPerformed(evt);
            }
        });

        WorkingDirectoryMenuItem.setText("Choose working directory");
        WorkingDirectoryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkingDirectoryMenuItemActionPerformed(evt);
            }
        });
        MainMenuDropdown.add(WorkingDirectoryMenuItem);

        LogBuilderMenuItem.setText("Create new log file");
        LogBuilderMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBuilderMenuItemActionPerformed(evt);
            }
        });
        MainMenuDropdown.add(LogBuilderMenuItem);

        ExitMenuItem.setText("Exit");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        MainMenuDropdown.add(ExitMenuItem);

        MainMenuBar.add(MainMenuDropdown);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ToLabel)
                    .addComponent(FromLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ToDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ToMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ToYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(TotalMileageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalMileageOutputText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromLabel)
                    .addComponent(FromMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToYearComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ToLabel)
                        .addComponent(ToMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ToDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TotalMileageLabel)
                    .addComponent(TotalMileageOutputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FromMonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromMonthComboBoxActionPerformed
        updateDisplay();
    }//GEN-LAST:event_FromMonthComboBoxActionPerformed

    private void ToMonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToMonthComboBoxActionPerformed
        updateDisplay();
    }//GEN-LAST:event_ToMonthComboBoxActionPerformed

    private void FromYearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromYearComboBoxActionPerformed
        updateDisplay();
    }//GEN-LAST:event_FromYearComboBoxActionPerformed

    private void ToYearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToYearComboBoxActionPerformed
        updateDisplay();
    }//GEN-LAST:event_ToYearComboBoxActionPerformed

    private void FromDayComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromDayComboBoxActionPerformed
        updateDisplay();
    }//GEN-LAST:event_FromDayComboBoxActionPerformed

    private void ToDayComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToDayComboBoxActionPerformed
        updateDisplay();
    }//GEN-LAST:event_ToDayComboBoxActionPerformed

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    private void MainMenuDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuDropdownActionPerformed
        
    }//GEN-LAST:event_MainMenuDropdownActionPerformed

    private void WorkingDirectoryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkingDirectoryMenuItemActionPerformed
         
        int returnVal = WorkingDirectoryChooser.showOpenDialog(this);

        if (returnVal == WorkingDirectoryChooser.APPROVE_OPTION) {
            workingDirectory = WorkingDirectoryChooser.getSelectedFile().toPath();
            //This is where a real application would open the file.
            System.out.println("Working directory is " + workingDirectory.toString());
        } else {
            System.out.println("Change working directory cancelled.");
        }
    }//GEN-LAST:event_WorkingDirectoryMenuItemActionPerformed

    private void LogBuilderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBuilderMenuItemActionPerformed
        LogBuilderCompleteNotification.setVisible(false);
        LogBuilderFrame.setVisible(true);
    }//GEN-LAST:event_LogBuilderMenuItemActionPerformed

    private void LogBuilderBuildButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBuilderBuildButtonActionPerformed
        //check that filename field contains something
        if (!LogBuilderNameField.getText().isEmpty() && !LogBuilderYearField.getText().isEmpty()) {
            //capture selections/text from other fields in the GUI
            filename = LogBuilderNameField.getText() + ".txt";
            yearToBuildString = LogBuilderYearField.getText();

            //check if filename exists, and prompt for overwrite if it does
            newFile = Paths.get(workingDirectory.toString() + File.separator + filename);
            if (Files.exists(newFile))
            {
                System.out.println("Filename already exists...");
                // pop-up box to notify and ask for overwrite permission
                //wait for next action from pop-up box
                //if yes, set mustDeleteFile "true" and call instantiateAndBuild
                int n = JOptionPane.showConfirmDialog(LogBuilderFrame,
                        newFile.toString() + " already exists.\nOverwrite it?",
                        "Overwrite it?",
                        JOptionPane.YES_NO_OPTION);
                if (n == 0) {
                    mustDeleteFile = true;
                    instantiateAndBuild();
                }
                else {
                    //close the JOptionPane
                }
            }
            else {
                //instantiate LogBuilder, passing selections/text to its constructor
                instantiateAndBuild();
            }
        }
    }//GEN-LAST:event_LogBuilderBuildButtonActionPerformed

    private void LogBuilderCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBuilderCloseButtonActionPerformed
        LogBuilderFrame.setVisible(false);
    }//GEN-LAST:event_LogBuilderCloseButtonActionPerformed

    private void LogBuilderYearFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LogBuilderYearFieldKeyPressed
        LogBuilderCompleteNotification.setVisible(false);
    }//GEN-LAST:event_LogBuilderYearFieldKeyPressed

    private void LogBuilderNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LogBuilderNameFieldKeyPressed
        LogBuilderCompleteNotification.setVisible(false);
    }//GEN-LAST:event_LogBuilderNameFieldKeyPressed

    private void updateDisplay() {
        if (FromMonthComboBox.getSelectedItem() != null && ToMonthComboBox.getSelectedItem() != null
                && FromYearComboBox.getSelectedItem() != null && ToYearComboBox.getSelectedItem() != null
                && FromDayComboBox.getSelectedItem() != null && ToDayComboBox.getSelectedItem() != null) {
            
                try {
                    MileageAdder adder = new MileageAdder(
                        FromDayComboBox.getSelectedItem().toString(),
                        FromMonthComboBox.getSelectedItem().toString(),
                        FromYearComboBox.getSelectedItem().toString(),
                        ToDayComboBox.getSelectedItem().toString(),
                        ToMonthComboBox.getSelectedItem().toString(),
                        ToYearComboBox.getSelectedItem().toString());

                    TotalMileageOutputText.setText(Integer.toString((int)adder.getTotalMileage()));
                    avgWeeklyMileage = adder.getWeeklyMileage();
                }
                catch (InvalidDateRangeException e1) {
                    System.out.println(e1.getMessage());
                    TotalMileageOutputText.setText("Invalid");
                    avgWeeklyMileage = 0;
                }
                catch (IOException e2) {
                    System.out.println(e2.getMessage());
                    TotalMileageOutputText.setText("0");
                    avgWeeklyMileage = 0;
                }
                finally {
                    weeklyPanel.repaint();
                }
        }
    }
    
    private void instantiateAndBuild() {
        //pass inputs to LogBuilder constructor
        LogBuilder tempBuilder = new LogBuilder(newFile, yearToBuildString, mustDeleteFile);
        
        //execute the logic to build the file
        tempBuilder.buildIt();
        
        //check for completion and notify the user
        LogBuilderCompleteNotification.setVisible(tempBuilder.wasBuildSuccessful());
        mustDeleteFile = false;
    }
    
    private class WeeklyMileagePanel extends javax.swing.JPanel {
        @Override
        public void paintComponent(Graphics g) { //invoked when the panel is added initially, when the window goes off screen and comes back, or when repaint is called 
            super.paintComponent(g);
            
            if(avgWeeklyMileage < 10)
                g.setColor(Color.red);
            else if (avgWeeklyMileage < 15)
                g.setColor(Color.orange);
            else if (avgWeeklyMileage < 20)
                g.setColor(Color.yellow);
            else if (avgWeeklyMileage < 25)
                g.setColor(Color.green);
            else
                g.setColor(Color.blue);

            g.fillRect(0, 0, (int)(avgWeeklyMileage * 5), 30);
            g.setColor(Color.black);
            g.drawString("Avg. week: " + Integer.toString((int)avgWeeklyMileage) + " miles", 10, 20);
        }   
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MileageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MileageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MileageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MileageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                workingDirectory = Paths.get("temp").toAbsolutePath().getParent();
                new MileageUI().setVisible(true);
            }
        });
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JComboBox FromDayComboBox;
    private javax.swing.JLabel FromLabel;
    private javax.swing.JComboBox FromMonthComboBox;
    private javax.swing.JComboBox FromYearComboBox;
    private javax.swing.JButton LogBuilderBuildButton;
    private javax.swing.JButton LogBuilderCloseButton;
    private javax.swing.JLabel LogBuilderCompleteNotification;
    private javax.swing.JFrame LogBuilderFrame;
    private javax.swing.JMenuItem LogBuilderMenuItem;
    private javax.swing.JTextField LogBuilderNameField;
    private javax.swing.JLabel LogBuilderNameLabel;
    private javax.swing.JLabel LogBuilderTxtLabel;
    private javax.swing.JTextField LogBuilderYearField;
    private javax.swing.JLabel LogBuilderYearLabel;
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JMenu MainMenuDropdown;
    private javax.swing.JComboBox ToDayComboBox;
    private javax.swing.JLabel ToLabel;
    private javax.swing.JComboBox ToMonthComboBox;
    private javax.swing.JComboBox ToYearComboBox;
    private javax.swing.JLabel TotalMileageLabel;
    private javax.swing.JTextField TotalMileageOutputText;
    private javax.swing.JFileChooser WorkingDirectoryChooser;
    private javax.swing.JMenuItem WorkingDirectoryMenuItem;
    // End of variables declaration//GEN-END:variables
}
